// 授权成功
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
// 授权拒绝
const USER_AUTH_REFUSED = 'USER_AUTH_REFUSED'
// 大厅用户私聊消息
const GET_USER_MESSAGE = 'GET_USER_MESSAGE'
// 加入大厅房间
const JOIN_HALL_ROOM = 'JOIN_HALL_ROOM'
// 退出大厅房间
const EXIT_HALL_ROOM = 'EXIT_HALL_ROOM'
// 加载状态
const LOADING_CHANGE = 'LOADING_CHANGE'
// 重新登录
const RELOGIN = 'RELOGIN'
// 房间ID
const ROOM_ID = 'ROOM_ID'
// 大厅房间在线人员总数
const HALL_ROOM_MEMBER_COUNT = 'HALL_ROOM_MEMBER_COUNT'
// 房间人数改变
const MEETER_ROOM_COUNT_CHANGE = 'MEETER_ROOM_COUNT_CHANGE'
// 房间属性
const ROOM_ATTRIBUTES = 'ROOM_ATTRIBUTES'
// 加入会议房间
const JOIN_MEETER_ROOM = 'JOIN_MEETER_ROOM'
// 退出会议房间
const EXIT_MEETER_ROOM = 'EXIT_MEETER_ROOM'
// 会议房间内在线人数
const MEETER_ROOM_COUNT = 'MEETER_ROOM_COUNT'
// 房间消息
const MEETER_ROOM_MESSAGE = 'MEETER_ROOM_MESSAGE'
// 创建房间
const CREATE_MEETER_ROMM = 'CREATE_MEETER_ROMM'
// 切换摄像头
const SWITCH_CAMERA = 'SWITCH_CAMERA'
// 切换静音模式
const SWITCH_MUTE = 'SWITCH_MUTE'
// 离开房间
const LEAVE_ROOM = 'LEAVE_ROOM'
// 主播退出房间
const OWNER_LEAVE_ROOM = 'OWNER_LEAVE_ROOM'
// 当前用户主播短线超时离开房间
const MEETER_OWNER_USER_OFFLINE = 'MEETER_OWNER_USER_OFFLINE'
// 房间用户断线退出房间
const ROOM_MEMBER_OFFLINE = 'ROOM_MEMBER_OFFLINE'
//
const HALL_ROOM_MEMBER_OFFLINE = 'HALL_ROOM_MEMBER_OFFLINE'

export {
  USER_AUTH_SUCCESS,
  USER_AUTH_REFUSED,
  GET_USER_MESSAGE,
  JOIN_HALL_ROOM,
  EXIT_HALL_ROOM,
  LOADING_CHANGE,
  RELOGIN,
  ROOM_ID,
  HALL_ROOM_MEMBER_COUNT,
  ROOM_ATTRIBUTES,
  JOIN_MEETER_ROOM,
  EXIT_MEETER_ROOM,
  MEETER_ROOM_COUNT,
  MEETER_ROOM_MESSAGE,
  MEETER_ROOM_COUNT_CHANGE,
  CREATE_MEETER_ROMM,
  SWITCH_CAMERA,
  SWITCH_MUTE,
  LEAVE_ROOM,
  OWNER_LEAVE_ROOM,
  ROOM_MEMBER_OFFLINE,
  MEETER_OWNER_USER_OFFLINE,
  HALL_ROOM_MEMBER_OFFLINE
}